### ISSUE TITLE
auro-skeleton: use of deprecated @alaskaairux/webcorestylesheets@3.7.3

### ISSUE THREAD

**Issue by ftaylor-alaska** [AlaskaAirlines/auro-skeleton#22] opened 2023-10-13 23:34 UTC
# General Support Request
This component has a dependency on a deprecated version of the wcss.

Please update from @alaskaairux/webcorestylesheets@3.7.3 to latest (@aurodesignsystem/webcorestylesheets@5.0.4 or later)

**Comment by blackfalcon** [comment] 2023-11-03 04:04
This project is still a Node 12 environment. We should do a complete update of the repo to support Node 20 and all dependencies.

**Comment by blackfalcon** [comment] 2023-11-09 23:44
This issue is a duplicate of 

- https://github.com/AlaskaAirlines/auro-skeleton/issues/23

**Closed by blackfalcon** 2023-11-09 23:44 UTC
Labels: duplicate, Status: Proposal, auro-skeleton
